// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvxfioewwfufcaonzhwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2eGZpb2V3d2Z1ZmNhb256aHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTM2OTIsImV4cCI6MjA2NjI2OTY5Mn0.VlDhdjprcj5uC7uE5HuW17nT2x-dgkx0Co9lpGDIaAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);