// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrpreofgewdlmuynyhxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycHJlb2ZnZXdkbG11eW55aHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTM0NjIsImV4cCI6MjA2NjI4OTQ2Mn0.NeqrOrrs5naYiLJKb2xACYG-ojVt2pMF4o-_lxgZVyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);